# Generated by Django 6.1 on 2026-09-06 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Shifokor', 'verbose_name_plural': 'Shifokorlar'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Ish jadvali', 'verbose_name_plural': 'Ish jadvallari'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': "Slot (Bo'sh vaqt)", 'verbose_name_plural': "Slotlar (Bo'sh vaqtlar)"},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Qabul yozuvi', 'verbose_name_plural': 'Qabul yozuvlari'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='complaint',
            field=models.TextField(blank=True, verbose_name='Shikoyati'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eslatma yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.slot', verbose_name='Slot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('band', 'Band'), ('keldi', 'Keldi'), ('kelmadi', 'Kelmadi'), ('bekor', 'Bekor qilingan')], default='band', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='room',
            field=models.CharField(max_length=20, verbose_name='Xona raqami'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slot_minutes',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Slot vaqti (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.speciality', verbose_name='Mutaxassisligi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Tanaffus tugashi'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Tanaffus boshlanishi'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor', verbose_name='Shifokor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor', verbose_name='Shifokor'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(verbose_name='Tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name="Bo'shmi"),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(verbose_name='Boshlanish vaqti'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name="Yo'nalish nomi"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('registrator', 'Registrator'), ('shifokor', 'Shifokor'), ('bemor', 'Bemor')], default='bemor', max_length=20, verbose_name='Roli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.appointment', verbose_name='Navbat'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(verbose_name='Tashxis'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Tavsiya'),
        ),
    ]
